### ISSUE TITLE
NewAccountTypePopup buttons doesn't reflect the tap action visually

### ISSUE THREAD

**Issue by albertopeam** [cosmostation/cosmostation-ios#102]
Hi, 

I have installed the app in the AppStore and I saw that the NewAccountTypePopup buttons doesn't show the highlight while tapping them.
I would like to fix them by my own, I have check the readme and I didn't find any doc about how to contribute. Could you explain where I can read something to getting started?

I would also ask if you can help me with the Xcode build as it is failing, reasons:
1. When I build the CosmostationDev target it gets stuck indefinitely(During "copy InfoPlist.strings"). 
2. It also throws an error related "GoogleService-Info.plist"(not found), could you explain if its needed some config related to firebase?

Relevant info:
I had an issue with Cocoapods while installing, I solved it with "gem install --user-install ffi -- --enable-libffi-alloc"
Finally I got all pods installed succesfully

Using:
M1 laptop. macOS 12.5.1 (21G83)
Xcode13.4.1
Cocoapods 1.11.3 / ruby 2.6.8p205 (2021-07-07 revision 67951)

I hope you can help me, I would like to contribute to this great project :)

**Comment by wannabit-yongjoo** [comment]
Thanks a lot for feedback. :)

**Comment by wannabit-yongjoo** [comment]
@soaryong-c

**Comment by albertopeam** [comment]
Hi!

Can I collaborate in the project if I find some issue like this or is open sourced but only to analyze the code? It wasn’t clear after reading your response as it seems you are going to handle it :)
In case is open to collaborate, where can I find relevant doc about how to contribute or similar?

About the compilation issue, what do you mean by update dev mode build config?  :)

Regards, Alberto :)

**Comment by wannabit-yongjoo** [comment]
Hi @albertopeam

**Comment by soaryong-c** [comment]
You can build by following these instructions:
1. Clone the project.
2. `pod update` ( in m1. `arch -x86_64 pod update`)
3. Remove **GoogleService-Info.plist** from list of project files.(Red highlighting)
4. Comment out `FirebaseApp.configure()` in **AppDelegate.swift**

@albertopeam
