### ISSUE TITLE
Add mock GoogleService-Info.plist as default values

### ISSUE THREAD

**Issue by professionallyatortoise** [cosmostation/cosmostation-ios#105]
This project does not build unless you add this a GoogleSerice-Info.plist file to the Cosmostation repo 

Should insert this mock plist from firebase just to get it up and running instead of having everyone figure this out independently. 
https://github.com/firebase/quickstart-ios/blob/master/mock-GoogleService-Info.plist

**Comment by soaryong-c** [comment]
You can build by following these instructions:
1. Clone the project.
2. `pod update` ( in m1. `arch -x86_64 pod update`)
3. Remove **GoogleService-Info.plist** from list of project files.(Red highlighting)
4. Comment out `FirebaseApp.configure()` in **AppDelegate.swift**

@albertopeam

**Comment by professionallyatortoise** [comment]
@soaryong-c 

Can we add this to the readme?

Contributors should have as little friction as possible when getting started.

**Comment by soaryong-c** [comment]
@professionallyatortoise 
thank you. 
https://github.com/cosmostation/cosmostation-ios/commit/3bbcf74b522a54528c9087a36ddc98b0fb99e519
