### ISSUE TITLE
Protobuff Documentation

### ISSUE THREAD

**Issue by Yselli** [cosmostation/cosmostation-ios#189]
Hello guys,
I am working on an iOS App that relies on the Protobuff code from the Cosmostation iOS repository. I would like to query all information about a CW20 token contract like symbol or name on Juno chain.
I've seen that you guys implemented a query to fetch the balance for a wallet and I was wondering if you could send me the documentation about how to query these endpoints. I searched for it already but without success.
I would highly appreciate it if you could support!

![Screenshot 2022-12-04 at 22 24 04](https://user-images.githubusercontent.com/49034642/205516451-a508cd24-37d5-4226-95c1-affd03c141df.png)
![Screenshot 2022-12-04 at 22 24 34](https://user-images.githubusercontent.com/49034642/205516471-99789e22-4bc5-47fb-aa98-923128f39d5d.png)

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-ios/blob/master/Cosmostation/Controller/Main/MainTabViewController.swift#L1068

**Comment by wannabit-yongjoo** [comment]
that line is query for cw20 balance with gRPC

**Comment by Yselli** [comment]
Yes, since you implemented it the c20 balance query successfully I asked for a documentation of the gRPC endpoints. I assume you have one.

**Comment by wannabit-yongjoo** [comment]
Contract calls and queries are all in that grpc.
The rest follows the syntax of the contract.
There is no choice but to communicate in binary (query data).

**Comment by wannabit-yongjoo** [comment]
https://github.com/CosmWasm/wasmd/blob/main/proto/cosmwasm/wasm/v1/query.proto

**Comment by Yselli** [comment]
Where can I find the contract details tho? For example for the SmartContractStateRequest. How do I know what fields are offered that I can query for?

**Comment by Yselli** [comment]
@wannabit-yongjoo friendly reminder :)

**Comment by wannabit-yongjoo** [comment]
Oh I see :0 soory for miss understanding
You means how to check contract that deployed in Juno chain
And which field we can query about contract?

We crawling all deployed contract in juno chain.
some contract is famous like cw20(https://github.com/CosmWasm/cw-tokens)
so we can check query param

but some special contract case we don't know even crawling.
that need ABI file like eth. 

@chicrock

**Comment by chicrock** [comment]
@Yselli There is no way to easy to query. Cause all contracts can have different code.

If you want to know the all structure of the contract, you should get the origin code of the contract.
After get the code of the contract, find the `ExecuteMsg` of that contract.
That is the all message types of the contract.
Or you can get the schemes of that contract via build.
You can see the example of schema and origin code in Mintscan. (https://www.mintscan.io/juno/wasm/code/59)

If you cannot get the origin code of the contract, you can get only states of the contract by guess. (Not Tx..Just state query)
