### ISSUE TITLE
Station Testnet Faucet

### ISSUE THREAD

**Issue by Yselli** [cosmostation/cosmostation-ios#222]
Is there a faucet for the Cosmostation Testnet?

https://testnet.mintscan.io/station
https://api.mintscan.io/v1/utils/params/chain/station

**Comment by soaryong-c** [comment]
currently unavailable.
If you need a token, leave your address and we will send you a test token.

**Comment by Yselli** [comment]
Ah ok, alternatively I could also use another testnet like Cosmos Theta. I would like to implement a ChainConfig for this. 
Is there a grpcUrl, lcdUrl and apiUrl equivalent to the mainnet ones?

    var grpcUrl = "grpc-cosmos.cosmostation.io"
    var grpcPort = 443
    var lcdUrl = "https://lcd-cosmos-app.cosmostation.io/"
    var apiUrl = "https://api-cosmos.cosmostation.io/"

**Comment by albertopeam** [comment]
It would be great to have a testnet
