### ISSUE TITLE
Protobuf & GRPC code generation

### ISSUE THREAD

**Issue by albertopeam** [cosmostation/cosmostation-ios#280]
I was working on a [repo](https://github.com/albertopeam/cosmos-sdk-swift) where we can have versioned all the cosmos and other chains protos and services. It is not prepared at all, only cosmos and osmosis are integrated.
What do you think about start using it? I mean when it is ready. @wannabit-yongjoo @soaryong-c

**Comment by wannabit-yongjoo** [comment]
@albertopeam 
Wow its great!
now we using[ custom repo](https://github.com/cosmostation/proto_collections) for proto files for each chains.
looks your working is more generic and easy to using.

please give your opinions @soaryong-c @Kwonhyukjoon

**Comment by albertopeam** [comment]
I didn't know about about this repo, I will take a look :)
