### ISSUE TITLE
Incorrect starname validation check

### ISSUE THREAD

**Issue by xpt1x** [cosmostation/cosmostation-ios#294]
This check is not good:
https://github.com/cosmostation/cosmostation-ios/blob/a6c6f75e302f6ebc674bcf22f2b6b2ca33b9ee63/Cosmostation/Controller/Main/starname/StarNameListViewController.swift#L52

Instead it should be: (writing in typescript, dont knw swift :sweat_smile: )
```ts
    const names = starname.split("*");
    if (names.length !== 2) return false;
    if (names[0] === "") return isStarnameValidDomain(names[1]);
    return isStarnameValidAccount(names[0]) && isStarnameValidDomain(names[1]);
```

Also please update this domain regex:
https://github.com/cosmostation/cosmostation-ios/blob/a6c6f75e302f6ebc674bcf22f2b6b2ca33b9ee63/Cosmostation/Controller/Main/starname/StarNameListViewController.swift#L59

Updated one is this: `"^[mabcdefghijklnopqrstuvwxyz0123456789][-a-z0-9_]{0,2}$|^[-a-z0-9_]{4,32}$"`
And can be found here: https://api.starname.cosmos.iov.one/starname/v1beta1/configuration/params

**Comment by Kwonhyukjoon** [comment]
IOS & And side bug fixed
Thanks a lot @xpt1x
