### ISSUE TITLE
Ledger Support for Mobile

### ISSUE THREAD

**Issue by sspage** [cosmostation/cosmostation-ios#39]
Please add Ledger support for mobile wallets.  Right now this is only supported on the web wallet.

**Comment by gickyDEV** [comment]
Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.

**Comment by sspage** [comment]
Ledger can't update the Cosmostation wallet.  This team needs to decide to do that.

**Comment by sspage** [comment]
> Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.

Ledger can't update the Cosmostation wallet. This team needs to decide to do that.

**Comment by wannabit-yongjoo** [comment]
> 

yes correct.
we have some plan for ledger device user, but There are many internal differences.

**Comment by alokc83** [comment]
@gickyDEV  except may be delegation why would you use cosmos if you have moved them to ledger. I think it may be more beneficial as Ledger are pretty good accepting request from user.

**Comment by troian** [comment]
i think there are some confusion going on. The request is to support Ledger device, not Ledger Live.

Using device to sign transactions is way more secure.
