### ISSUE TITLE
Secret-4 chain

### ISSUE THREAD

**Issue by Life-maps** [cosmostation/cosmostation-ios#5]
How to add secret-4 chain to secret wallet? Latest version is secret-3 chain which is dead—can not operate Wallet features without errors. 

 This chain is dead and some features may not work. Want to see the latest chain?

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-ios/commit/8374d7383440dd2f691e48556910b7d76d2f6a53
